image: ubuntu:bionic

variables:
  GIT_SUBMODULE_STRATEGY: recursive

tests:
  before_script:
    # Install Git and GNU Make
    - apt-get update -yqq
    - apt-get install -yqq git make unzip
    # TODO: Figure out a way to intall these system packages as dependecies of
    # the targets that use them.
    - apt-get install -yqq python3-minimal python3-pip python3-yaml python3-jinja2 python3-apt
    - pip3 install ntfy[matrix]
    - update-alternatives --install /usr/bin/python python /usr/bin/python3 1
    - make ansible
  script:
    - source d
    - make ansible-role-test; RESULT=$? make -s ntfy-ci
