image: ubuntu:bionic

variables:
  GIT_SUBMODULE_STRATEGY: recursive
  # Overcome world-writeable dir complaints. See:
  # https://docs.ansible.com/ansible/devel/reference_appendices/config.html#cfg-in-world-writable-dir
  ANSIBLE_CONFIG: ansible.cfg
  DEBIAN_FRONTEND: noninteractive

tests:
  before_script:
    # Install Git and GNU Make
    - apt-get update -yqq
    - apt-get install -yqq git make unzip
    # TODO: Figure out a way to intall these system packages as dependecies of
    # the targets that use them.
    - apt-get install -yqq python3-minimal python3-pip python3-yaml python3-jinja2 python3-apt
    - pip3 install ntfy[matrix]
    - update-alternatives --install /usr/bin/python python /usr/bin/python3 1
    - make ansible
  script:
    - source d
    - git clone https://gitlab.com/consensus.enterprises/ansible-roles/ansible-role-mysql.git tests/roles/geerlingguy.mysql
    - ANSIBLE_TEST_PLAYBOOK=tests/unit-tests.yml make ansible-role-test #TODO: notify is busted somehow, no time to fix; make -s ntfy-ci NOTIFY_CI_RESULT=$?
