image: ubuntu:focal

stages:
  - test

variables:
  GIT_SUBMODULE_STRATEGY: recursive
  # Overcome world-writeable dir complaints. See:
  # https://docs.ansible.com/ansible/devel/reference_appendices/config.html#cfg-in-world-writable-dir
  ANSIBLE_CONFIG: ansible.cfg
  DEBIAN_FRONTEND: noninteractive

deb-default: &test-defaults
  variables:
    ANSIBLE_TEST_PLAYBOOK: tests/deb-default.yml
  stage: test
  before_script:
    # Install Git and GNU Make
    - apt-get update -yqq
    - apt-get install -yqq git make unzip
    # TODO: Figure out a way to install these system packages as dependecies of
    # the targets that use them.
    - apt-get install -yqq python3-minimal python3-pip python3-yaml python3-jinja2 python3-apt
    - update-alternatives --install /usr/bin/python python /usr/bin/python3 1
    - pip3 install jinja2-cli matrix-client
    - make ansible
    # Necessary to get `ansible-galaxy`.
    - apt-get install --assume-yes ansible
    # Fetch role dependencies
    - git clone https://github.com/consensus-enterprises/ansible-role-mysql.git tests/roles/consensus.mysql
    - git clone https://gitlab.com/consensus.enterprises/ansible-roles/ansible-role-nginx.git tests/roles/geerlingguy.nginx
    - git clone https://github.com/consensus-enterprises/ansible-role-php.git tests/roles/consensus.php
    # Fetch collection dependencies
    - ansible-galaxy collection install community.crypto community.general
    # Make our base URL resolve.
    - echo `hostname -I` aegir.local >> /etc/hosts

  script:
    - source d
    - make ansible-role-test; make -s matrix-ci NOTIFY_CI_RESULT=$?

deb-nginx:
  <<: *test-defaults
  variables:
    ANSIBLE_TEST_PLAYBOOK: tests/deb-nginx.yml

git-deploy:
  <<: *test-defaults
  variables:
    ANSIBLE_TEST_PLAYBOOK: tests/git-deploy.yml

custom-deploy:
  <<: *test-defaults
  variables:
    ANSIBLE_TEST_PLAYBOOK: tests/custom-deploy.yml
    extra_vars: aegir_skynet_enable=False

custom-upgrade:
  <<: *test-defaults
  variables:
    ANSIBLE_TEST_PLAYBOOK: tests/custom-deploy.yml
    extra_vars: aegir_skynet_enable=False
  script:
    - source d
    - make ansible-role-test
    - make ansible-role-test ANSIBLE_TEST_PLAYBOOK=tests/upgrade.yml; make -s matrix-ci NOTIFY_CI_RESULT=$?

image-deploy:
  <<: *test-defaults
  variables:
    ANSIBLE_TEST_PLAYBOOK: tests/image-deploy.yml

unit-tests:
  <<: *test-defaults
  variables:
    ANSIBLE_TEST_PLAYBOOK: tests/unit-tests.yml
    extra_vars: aegir_skynet_enable=False

