image: ubuntu:bionic

stages:
  - test

variables:
  GIT_SUBMODULE_STRATEGY: recursive
  # Overcome world-writeable dir complaints. See:
  # https://docs.ansible.com/ansible/devel/reference_appendices/config.html#cfg-in-world-writable-dir
  ANSIBLE_CONFIG: ansible.cfg
  DEBIAN_FRONTEND: noninteractive

deb-default: &test-defaults
  variables:
    ANSIBLE_TEST_PLAYBOOK: tests/deb-default.yml
  stage: test
  before_script:
    # Install Git and GNU Make
    - apt-get update -yqq
    - apt-get install -yqq git make unzip
    # TODO: Figure out a way to install these system packages as dependecies of
    # the targets that use them.
    - apt-get install -yqq python3-minimal python3-pip python3-yaml python3-jinja2 python3-apt
    - pip3 install ntfy[matrix]
    - update-alternatives --install /usr/bin/python python /usr/bin/python3 1
    - make ansible
    # Fetch role dependencies
    - git clone https://gitlab.com/consensus.enterprises/ansible-roles/ansible-role-mysql.git tests/roles/geerlingguy.mysql
    - git clone https://gitlab.com/consensus.enterprises/ansible-roles/ansible-role-nginx.git tests/roles/geerlingguy.nginx
    - git clone https://gitlab.com/consensus.enterprises/ansible-roles/ansible-role-php.git tests/roles/geerlingguy.php
    # Make our base URL resolve.
    - echo `hostname -I` aegir.local >> /etc/hosts

  script:
    - source d
    - make ansible-role-test #TODO: notify is busted somehow, no time to fix; make -s ntfy-ci NOTIFY_CI_RESULT=$?

deb-nginx:
  <<: *test-defaults
  variables:
    ANSIBLE_TEST_PLAYBOOK: tests/deb-nginx.yml

git-deploy:
  <<: *test-defaults
  variables:
    ANSIBLE_TEST_PLAYBOOK: tests/git-deploy.yml

custom-deploy:
  <<: *test-defaults
  variables:
    ANSIBLE_TEST_PLAYBOOK: tests/custom-deploy.yml
    EXTRA_VARS: aegir_skynet_enable=False

custom-upgrade:
  <<: *test-defaults
  variables:
    ANSIBLE_TEST_PLAYBOOK: tests/custom-deploy.yml
    EXTRA_VARS: aegir_skynet_enable=False
  script:
    - source d
    - make ansible-role-test
    - make ansible-role-test EXTRA_VARS="${EXTRA_VARS} aegir_platform_version=upgraded-platform"

unit-tests: 
  <<: *test-defaults
  variables:
    ANSIBLE_TEST_PLAYBOOK: tests/unit-tests.yml 
    EXTRA_VARS: aegir_skynet_enable=False

