---
language: php

dist: trusty

addons:
  apt:
    sources:
    - sourceline: 'ppa:ondrej/php'

matrix:
  include:
    # Check every combination of deb/git, php5/php7.0 and nginx/apache
    - php: 5.6
      env: INSTALL_METHOD=git PHP_VERSION=5 HTTP_SERVICE=nginx
    - php: 5.6
      env: INSTALL_METHOD=git PHP_VERSION=5 HTTP_SERVICE=apache
    - php: 5.6
      env: INSTALL_METHOD=deb PHP_VERSION=5 HTTP_SERVICE=nginx
    - php: 5.6
      env: INSTALL_METHOD=deb PHP_VERSION=5 HTTP_SERVICE=apache
    - php: 7.0
      env: INSTALL_METHOD=git PHP_VERSION=7.0 HTTP_SERVICE=nginx
    - php: 7.0
      env: INSTALL_METHOD=git PHP_VERSION=7.0 HTTP_SERVICE=apache
    # This test fails because Apache is being installed. This may have
    # something to do with the PPA added to allow PHP 7.0. We should test on
    # Ubuntu Xenial or some other environment where PHP 7.0 is the default.  -
    #- php: 7.0
    #  env: INSTALL_METHOD=deb PHP_VERSION=7.0 HTTP_SERVICE=nginx
    - php: 7.0
      env: INSTALL_METHOD=deb PHP_VERSION=7.0 HTTP_SERVICE=apache

env:
  global:
    - ANSIBLE_ROLES_PATH=tests/roles
    - ANSIBLE_REQUIREMENTS=tests/requirements.yml
    - ANSIBLE_PLAYBOOK=tests/playbook.yml
    - LAST_KNOWN_GOOD_DRUSH=8.1.3

install:
  - sudo make deps-ansible
  - pip install pyyaml jinja2
  - make ansible

script:
  # Bootstrap Drumkit
  - ". d"

  # Set extra vars
  - export ANSIBLE_EXTRA_VARS="aegir_install_method=$INSTALL_METHOD aegir_php_version=$PHP_VERSION aegir_http_service_type=$HTTP_SERVICE aegir_drush_version=$LAST_KNOWN_GOOD_DRUSH"

  # Run playbook tests
  - make ansible-playbook-test-idempotence

  # Check Aegir is installed and working.
  - sudo -u aegir -H drush @hm status | grep eldir

  # Check that correct HTTP server was installed.
  - sudo -u aegir -H drush @server_master eval 'drush_print_r(d()->http_service_type);' | grep $HTTP_SERVICE

