---
language: python
python: "2.7"

dist: trusty

env:
  global:
    - ANSIBLE_ROLES_PATH=tests/roles
    - ANSIBLE_REQUIREMENTS=tests/requirements.yml
    - ANSIBLE_PLAYBOOK=tests/playbook.yml
  matrix:
    # Check every combination of deb/git, php5/php7.0 and nginx/apache
    - ANSIBLE_EXTRA_VARS="aegir_install_method=git aegir_php_version=7.0 aegir_http_service_type=nginx"
    - ANSIBLE_EXTRA_VARS="aegir_install_method=git aegir_php_version=7.0 aegir_http_service_type=apache"
    - ANSIBLE_EXTRA_VARS="aegir_install_method=git aegir_php_version=5 aegir_http_service_type=nginx"
    - ANSIBLE_EXTRA_VARS="aegir_install_method=git aegir_php_version=5 aegir_http_service_type=apache"
    - ANSIBLE_EXTRA_VARS="aegir_install_method=deb aegir_php_version=7.0 aegir_http_service_type=nginx"
    - ANSIBLE_EXTRA_VARS="aegir_install_method=deb aegir_php_version=7.0 aegir_http_service_type=apache"
    - ANSIBLE_EXTRA_VARS="aegir_install_method=deb aegir_php_version=5 aegir_http_service_type=nginx"
    - ANSIBLE_EXTRA_VARS="aegir_install_method=deb aegir_php_version=5 aegir_http_service_type=apache"


install:
  - sudo make deps-ansible
  - pip install pyyaml jinja2
  - make ansible

script:
  # Bootstrap Drumkit
  - ". d"

  # Run playbook tests
  - make ansible-playbook-test-idempotence

  # Check Aegir is installed and working.
  - sudo -u aegir -H drush @hm status | grep eldir

