---

- name: Ensure Skynet's dependencies are installed.
  apt:
    state: present
    name: "{{ aegir_skynet_dependencies }}"
  become: yes

- name: Install Cement
  pip:
    name: cement
    state: present
    executable: pip3
    break_system_packages: true
  become: yes
