---

- name: Enable Skynet module
  include_tasks: ../extra-modules.yml
  vars:
    aegir_extra_modules:
      - hosting_skynet

- name: Force task queue to run.
  shell: drush @hostmaster hosting-task @hostmaster verify --force
  become: yes
  become_user: "{{ aegir_user }}"

- name: Wait until the Skynet script is deployed.
  wait_for:
    path: "{{ aegir_skynet_bin_path }}"

- name: Ensure Skynet script is executable.
  file:
    path: "{{ aegir_skynet_bin_path }}"
    mode: "740"
  become: yes
  become_user: "{{ aegir_user }}"
