---

- name: Enable Skynet module
  include: ../extra-modules.yml
  vars:
    aegir_extra_modules:
      - hosting_skynet

- name: Wait until the Skynet script is deployed.
  wait_for:
    path: "{{ default_aegir_skynet_bin_path }}"

