---

# TODO: document why we need to do this.

- name: Ensure composer upgrade dependency php-psr-log is installed # we can install this one via apt
  tags: composer-upgrade
  apt:
    name: php-psr-log
    update_cache: yes
    cache_valid_time: 3600
  become: yes

## These are the current Ubuntu Bionic packages. Note sure why we'd need to install them this way...
- name: Ensure composer upgrade deb packages are installed # we must download these 3 and force install with dpkg
  tags: composer-upgrade
  apt:
    deb: "{{ item }}"
    dpkg_options: 'force-confold,force-confdef,force-overwrite'
  become: yes
  loop:
    - 'http://mirrors.kernel.org/ubuntu/pool/universe/p/php-composer-ca-bundle/php-composer-ca-bundle_1.1.0-1_all.deb'
    - 'http://mirrors.kernel.org/ubuntu/pool/universe/p/php-composer-spdx-licenses/php-composer-spdx-licenses_1.3.0-1_all.deb'
    - 'http://mirrors.kernel.org/ubuntu/pool/universe/c/composer/composer_1.6.3-1_all.deb'

