---
- include: deb/repo.yml
- include: deb/utils.yml
- include: deb/debconf.yml

# Ref.: https://gitlab.com/consensus.enterprises/ansible-roles/ansible-role-aegir/-/issues/3
- name: Create 'aegir' user key pair.
  include: generate-keypair.yml
  when: aegir_generate_keypair | bool

- include: deb/install.yml
