---
- name: Ensure Aegir's common dependencies are installed.
  apt:
    name: "{{ aegir_dependencies }}"
    state: present

- name: Ensure Aegir's PHP 5 dependencies are installed.
  apt:
    name: "{{ aegir_dependencies_php5 }}"
    state: present
  when: (aegir_php_version == '5')

- name: Ensure Aegir's PHP 7 dependencies are installed.
  apt:
    name: "{{ aegir_dependencies_php7 }}"
    state: present
  when: (aegir_php_version == '7')

- name: Ensure Aegir's NGINX dependencies for PHP 5 are installed.
  apt:
    name: "{{ aegir_dependencies_nginx_php5 }}"
    state: present
  when: (aegir_http_service_type == 'nginx') and (aegir_php_version == '5')

- name: Ensure Aegir's NGINX dependencies for PHP 7 are installed.
  apt:
    name: "{{ aegir_dependencies_nginx_php7 }}"
    state: present
  when: (aegir_http_service_type == 'nginx') and (aegir_php_version == '7')

- name: Ensure Aegir's Apache dependencies for PHP 5 are installed.
  apt:
    name: "{{ aegir_dependencies_apache_php5 }}"
    state: present
  when: (aegir_http_service_type == 'apache') and (aegir_php_version == '5')

- name: Ensure Aegir's Apache dependencies for PHP 7 are installed.
  apt:
    name: "{{ aegir_dependencies_apache_php7 }}"
    state: present
  when: (aegir_http_service_type == 'apache') and (aegir_php_version == '7')

