---
- name: Escalate privileges to install packages.
  become: yes
  block:
  - debug: var=aegir_http_service_type
  - name: Ensure Aegir's common dependencies are installed.
    apt:
      name: "{{ aegir_dependencies }}"
      state: present
  - name: Ensure Aegir's NGINX dependencies are installed.
    apt:
      name: "{{ aegir_dependencies_nginx }}"
      state: present
    when: aegir_http_service_type == 'nginx'
  - name: Ensure Aegir's Apache dependencies are installed.
    apt:
      name: "{{ aegir_dependencies_apache }}"
      state: present
    when: aegir_http_service_type == 'apache'
