---

- name: Find the hostmaster platform path.
  shell: drush @hm status --fields=root --field-labels=0
  become_user: "{{ aegir_user }}"
  become: true
  register: hostmaster_platform_path
  changed_when: false

- name: Set a fact for the hostmaster platform path
  set_fact:
    hostmaster_platform_path: "{{ hostmaster_platform_path.stdout | trim }}"

- name: Run the install script.
  shell: "/bin/bash {{ hostmaster_platform_path }}/profiles/hostmaster/modules/aegir/hosting_tasks_extra/fix_ownership/scripts/install.sh"
  args:
    creates: /etc/sudoers.d/fix-drupal-platform-ownership
  become: true
  become_user: root

- name: Check if fix_ownership module is enabled
  shell: "drush @hm pm-info --fields=status --format=list fix_ownership | egrep 'disabled|not installed'"
  become: True
  become_user: "{{ aegir_user }}"
  register: fix_ownership_enabled
  changed_when: False
  failed_when: False
  ignore_errors: yes

- name: Enable fix_ownership module
  command: "drush @hm --yes en fix_ownership --no-verify --strict=0"
  become: True
  become_user: "{{ aegir_user }}"
  when: fix_ownership_enabled.rc == 0
  notify: Verify Aegir front-end

