---
# Ref.: http://docs.aegirproject.org/en/3.x/install/#31-create-the-aegir-user
- name: Create 'aegir' group
  group:
    name: "{{ aegir_user }}"
    system: yes
- name: Create 'aegir' user
  user:
    name: "{{ aegir_user }}"
    system: yes
    home: "{{ aegir_root }}"
    group: "{{ aegir_user }}"
    groups: "{{ aegir_web_group }}"
    append: yes

# Ref.: http://docs.aegirproject.org/en/3.x/install/#41-install-drush
- name: Install Drush
  include: git/drush.yml
  when: aegir_install_drush

# Ref.: http://docs.aegirproject.org/en/3.x/install/#43-install-provision
- name: Create 'aegir' user home.
  file:
    path: /var/aegir/
    state: directory
    owner: "{{ aegir_user }}"
    group: "{{ aegir_user }}"
- name: Create ~/.drush/ for 'aegir' user.
  file:
    path: /var/aegir/.drush
    state: directory
    owner: "{{ aegir_user }}"
    group: "{{ aegir_user }}"
- name: Clone Provision
  git:
    repo: "{{ aegir_provision_repo }}"
    dest: "{{ aegir_root }}/.drush/provision"
    depth: 1 # speeds things up
    version: "{{ aegir_provision_version }}"
    update: "{{ aegir_provision_update }}"
  become: yes
  become_user: "{{ aegir_user }}"
- name: Clear Drush cache for Provision extension
  command: drush @none cc drush
  args:
    creates: "{{ aegir_root }}/.drush/cache/"
  become: yes
  become_user: "{{ aegir_user }}"

# Ref.: http://docs.aegirproject.org/en/3.x/install/#321-apache-configuration
- include: git/setup-apache.yml
  when: aegir_http_service_type == 'apache'

# Ref.: http://docs.aegirproject.org/en/3.x/install/#322-nginx-configuration
- include: git/setup-nginx.yml
  when: aegir_http_service_type == 'nginx'

# Ref.: http://docs.aegirproject.org/en/3.x/install/#34-sudo-configuration
- name: Configure sudo for aegir user
  copy:
    dest: "/etc/sudoers.d/{{ aegir_user }}"
    content: "{{ aegir_user }} ALL=NOPASSWD: /usr/sbin/apache2ctl\n{{ aegir_user }} ALL=NOPASSWD: /etc/init.d/nginx\n\n"
    mode: 0440

- name: Write Hostmaster makefile
  copy:
    dest: "{{ aegir_root }}/aegir.make"
    content: "{{ aegir_makefile_contents }}"
    owner: "{{ aegir_user }}"
    group: "{{ aegir_user }}"

- name: Build Hostmaster platform
  command: "drush make {{ aegir_root }}/aegir.make {{ aegir_root }}/hostmaster-{{ aegir_platform_version }} --working-copy --no-gitinfofile"
  args:
    creates: "{{ aegir_root }}/hostmaster-{{ aegir_platform_version }}/"
  become: yes
  become_user: "{{ aegir_user }}"

# Ref.: http://docs.aegirproject.org/en/3.x/install/#44-running-hostmaster-install
- name: Install Aegir front-end
  command: "drush @none --yes hostmaster-install --debug --working-copy --aegir_db_host={{ aegir_db_host | default('localhost') }} --aegir_db_user={{ aegir_db_user }} --aegir_db_pass={{ aegir_db_password }} --aegir_version={{ aegir_platform_version }} --http_service_type={{ aegir_http_service_type }} {{ aegir_frontend_url }} --strict=0 --root={{ aegir_root }}/hostmaster-{{ aegir_platform_version }}/"
  args:
    creates: "{{ aegir_root }}/hostmaster-{{ aegir_platform_version }}/sites/{{ aegir_frontend_url }}/"
  become: yes
  become_user: "{{ aegir_user }}"

