---
# Ref.: http://docs.aegirproject.org/en/3.x/install/#31-create-the-aegir-user
- name: Create 'aegir' user, group, home and Drush directories.
  include: git/user.yml

# Ref.: https://gitlab.com/consensus.enterprises/ansible-roles/ansible-role-aegir/-/issues/3
- name: Create 'aegir' user key pair.
  include: generate-keypair.yml
  when: aegir_generate_keypair | bool

# Ref.: http://docs.aegirproject.org/en/3.x/install/#41-install-drush
- name: Install Drush
  include: git/drush.yml
  when: aegir_install_drush | bool

# Ref.: http://docs.aegirproject.org/en/3.x/install/#43-install-provision
- name: Clone Provision
  include: git/provision.yml

# Ref.: http://docs.aegirproject.org/en/3.x/install/#321-apache-configuration
- name: Setup Apache.
  include: git/setup-apache.yml
  when: aegir_http_service_type == 'apache'

# Ref.: http://docs.aegirproject.org/en/3.x/install/#322-nginx-configuration
- name: Setup Nginx.
  include: git/setup-nginx.yml
  when: aegir_http_service_type == 'nginx'

# Ref.: http://docs.aegirproject.org/en/3.x/install/#34-sudo-configuration 
- name: Configure sudo for aegir user.
  include: git/sudo.yml

- name: Build hostmaster platform.
  include: git/platform.yml

- name: Fix permissions and ownership before site install.
  include: git/fix_permissions_and_ownership.yml

# Ref.: https://gitlab.com/consensus.enterprises/ansible-roles/ansible-role-aegir/-/issues/3

- debug:
    msg: "Stop right before front-end installation, if we've been asked to."
    when: aegir_stop_before_site_install | bool

- name: "Stop right before front-end installation, if we've been asked to."
  meta: end_play
  when: aegir_stop_before_site_install | bool

# Ref.: http://docs.aegirproject.org/en/3.x/install/#44-running-hostmaster-install
- name: Install Aegir front-end.
  include: git/install.yml

- name: Upgrade Aegir front-end.
  include: git/upgrade.yml
