---
- name: Install Aegir via Git.
  include: git.yml
  when: aegir_install_method == "git"

- name: Install Aegir via Debian packages.
  include: deb.yml
  when: aegir_install_method == "deb"

- name: Install additional packages.
  apt:
    name: "{{ item }}"
    state: installed
  when: (aegir_install_additional_packages == true) and (ansible_os_family == 'Debian')
  with_items: "{{ aegir_additional_packages }}"

- include: generate-keypair.yml
  when: aegir_generate_keypair

- name: Ensure Hosting is recognized as enabled
  shell: drush @hostmaster cc drush
  become: yes
  become_user: "{{ aegir_user }}"
  changed_when: False
