---
- meta: flush_handlers

- name: Ensure Aegir's dependencies are installed.
  include: dependencies.yml
  when: (aegir_manage_dependencies == true) and (ansible_os_family == 'Debian')

- name: Install additional packages.
  apt:
    name: "{{ aegir_additional_packages }}"
    state: present
  become: yes
  when: (aegir_install_additional_packages == true) and (ansible_os_family == 'Debian')

- name: Default Aegir database password to MySQL root password
  set_fact:
    aegir_db_password: "{{ mysql_root_password }}"
  when: (aegir_db_password is not defined) and (mysql_root_password is defined)

- name: Default Aegir database user to MySQL root user
  set_fact:
    aegir_db_user: "{{ mysql_root_user }}"
  when: (aegir_db_user is not defined) and (mysql_root_user is defined)

- name: Force upgrade of Composer.
  include: composer.yml
  when: aegir_upgrade_composer | bool

- name: Install Aegir via Git.
  include: git.yml
  when: aegir_install_method == "git"

- name: Install Aegir via Debian packages.
  include: deb.yml
  become: yes
  when: aegir_install_method == "deb"

- name: Enable extra modules.
  include: extra-modules.yml
  when: aegir_extra_modules | length > 0

- name: Perform miscellaneous tasks.
  include: misc.yml
  when: aegir_extra_config | bool

- include: generate-keypair.yml
  when: aegir_generate_keypair | bool

- include: fix_permissions.yml
  when: aegir_fix_permissions | bool

- include: fix_ownership.yml
  when: aegir_fix_ownership | bool

- include: registry_rebuild.yml
  when: aegir_registry_rebuild | bool

- name: Ensure Hosting is recognized as enabled
  shell: drush @none cc drush && drush @hostmaster cc drush
  become: yes
  become_user: "{{ aegir_user }}"
  changed_when: False

- include: login_link.yml
  when: aegir_login_link | bool
