---
- meta: flush_handlers

- name: Ensure Aegir's dependencies are installed.
  include: dependencies.yml
  when: aegir_manage_dependencies | bool

- name: Install additional packages.
  apt:
    name: "{{ aegir_additional_packages }}"
    state: present
  become: yes
  when: aegir_install_additional_packages | bool

- name: Default Aegir database password to MySQL root password
  set_fact:
    aegir_db_password: "{{ mysql_root_password_written }}"
  when: (aegir_db_password is not defined) and (mysql_root_password_written is defined)

- name: Default Aegir database user to MySQL root user
  set_fact:
    aegir_db_user: "{{ mysql_root_user }}"
  when: (aegir_db_user is not defined) and (mysql_root_user is defined)

- name: Generate Aegir Drush makefile.
  include: makefile.yml

- name: Install Aegir via Git.
  include: git.yml
  when: aegir_install_method == "git"

- name: Install Aegir via Debian packages.
  include: deb.yml
  become: yes
  when: aegir_install_method == "deb"

- name: Install global config file.
  include: global.yml

- name: Enable extra modules.
  include: extra-modules.yml
  when: aegir_extra_modules | length > 0

- name: Perform miscellaneous tasks.
  include: misc.yml
  when: aegir_extra_config | bool

- include: registry_rebuild.yml
  when: aegir_registry_rebuild | bool

- name: Temporarily allow globally readable Ansible command files for next task
  ansible.builtin.set_fact:
    ansible_shell_allow_world_readable_temp: yes

- name: Ensure Hosting is recognized as enabled.
  shell: drush @none cc drush && drush @hostmaster cc drush
  become: yes
  # See https://docs.ansible.com/ansible/latest/user_guide/become.html#risks-of-becoming-an-unprivileged-user
  become_user: "{{ aegir_user }}"
  changed_when: False

- name: Disable globally readable Ansible command files for previous task
  ansible.builtin.set_fact:
    ansible_shell_allow_world_readable_temp: no

- name: Deploy Skynet queue daemon.
  include: skynet.yml
  when: aegir_skynet_enable | bool

- include: login_link.yml
  when: aegir_login_link | bool
