---
- meta: flush_handlers

- name: Ensure Aegir's dependencies are installed.
  include_tasks: dependencies.yml
  when: aegir_manage_dependencies | bool

- name: Install additional packages.
  apt:
    name: "{{ aegir_additional_packages }}"
    state: present
  become: yes
  when: aegir_install_additional_packages | bool

- name: Default Aegir database password to MySQL root password
  set_fact:
    aegir_db_password: "{{ mysql_root_password_written }}"
  when: (aegir_db_password is not defined) and (mysql_root_password_written is defined)

- name: Default Aegir database user to MySQL root user
  set_fact:
    aegir_db_user: "{{ mysql_root_user }}"
  when: (aegir_db_user is not defined) and (mysql_root_user is defined)

- name: Generate Aegir Drush makefile.
  include_tasks: makefile.yml

- name: Install Aegir via Git.
  include_tasks: git.yml
  when: aegir_install_method == "git"

- name: Install Aegir via Debian packages.
  include_tasks: deb.yml
  when: aegir_install_method == "deb"

- name: Install global config file.
  include_tasks: global.yml

- name: Enable extra modules.
  include_tasks: extra-modules.yml
  when: aegir_extra_modules | length > 0

- name: Perform miscellaneous tasks.
  include_tasks: misc.yml
  when: aegir_extra_config | bool

- include_tasks: registry_rebuild.yml
  when: aegir_registry_rebuild | bool

- name: Ensure Hosting is recognized as enabled.
  shell: drush @none cc drush && drush @hostmaster cc drush
  become: yes
  become_user: "{{ aegir_user }}"
  changed_when: False

- name: Deploy Skynet queue daemon.
  include_tasks: skynet.yml
  when: aegir_skynet_enable | bool

- include_tasks: login_link.yml
  when: aegir_login_link | bool
