---
- name: Write makefile for Hostmaster platform.
  block:
  - name: Ensure Aegir settings path exists.
    file:
      state: directory
      path: "{{ aegir_etc_path }}"
      mode: 0755
  - name: Write Hostmaster makefile.
    template:
      dest: "{{ aegir_makefile_path }}"
      src: "{{ aegir_makefile_template }}"
      mode: 0644
  become: yes
  when: aegir_generate_makefile | bool

- name: Default to Aegir Drush makefile from Provision deployed from Git.
  set_fact:
    aegir_makefile_path: "{{ aegir_root }}/.drush/provision/aegir.make"
  when: (aegir_generate_makefile | bool == False) and (aegir_install_method == 'git')

- name: Default to Aegir Drush makefile from Provision deployed from Debian package.
  set_fact:
    aegir_makefile_path: "/usr/share/drush/commands/provision/aegir.make"
  when: (aegir_generate_makefile | bool == False) and (aegir_install_method == 'deb')
