---

- name: Deploy Provision from custom repo and/or branch.
  tags: provision-override
  become: true
  become_user: "{{ aegir_user }}"
  git:
    repo: "{{ aegir_provision_repo }}"
    dest: "{{ aegir_root }}/.drush/provision"
    update: "{{ aegir_provision_update }}"
    version: "{{ aegir_provision_version }}"
  register: provision_git_clone_result

- name: Override Provision shipped with Debian package.
  tags: provision-override
  template:
    src: files/local.drushrc.php.j2
    dest: "{{ aegir_root }}/.drush/local.drushrc.php"
    owner: "{{ aegir_user }}"
    group: "{{ aegir_user }}"
    mode: 0644
  notify:
    - Restart the queue daemon
    - Clear Aegir task queue lock

- block:
  - name: Clear Drush cache
    command: drush @none cc drush
  - name: Clear Aegir front-end Drush cache.
    shell: drush @hm cc drush
  - name: Re-verify default Aegir entities, to update w/ changes in custom Provision.
    tags: provision-override
    shell: "drush {{ item }} provision-verify"
    with_items:
      - "@server_master"
      - "@server_localhost"
      - "@platform_hostmaster"
      - "@hostmaster"
  become: yes
  become_user: "{{ aegir_user }}"
  when: provision_git_clone_result.changed | bool
