---
- name: Include Skynet dependency tasks.
  include_tasks: skynet/dependencies.yml

- name: Include Skynet sudo tasks.
  include_tasks: skynet/sudo.yml

- name: Include Skynet installation and deployment tasks.
  include_tasks: skynet/install.yml

- name: Include tasks for launching Skynet Systemd service.
  include_tasks: skynet/service.yml

# TODO: clean up legacy hosting queue daemon and supervisord config files if they exist
