---

- name: Deploy Provision from custom repo and/or branch.
  ansible.builtin.git:
    repo: "{{ aegir_provision_repo }}"
    dest: "{{ aegir_provision_directory }}"
    update: "{{ aegir_provision_update }}"
    version: "{{ aegir_provision_version }}"
    force: yes
  become: yes
  register: aegir_provision_git_deploy_result

- name: Make the Aegir user the owner of the Provision code
  ansible.builtin.file:
    path: "{{ aegir_provision_directory }}"
    state: directory
    recurse: yes
    owner: "{{ aegir_user }}"
    group: "{{ aegir_user }}"
  become: yes

- name: Temporarily allow globally readable Ansible command files for next task
  set_fact:
    allow_world_readable_tmpfiles: yes

- name: Clear Drush cache for Provision extension
  shell: drush @none cc drush
  become: yes
  # See https://docs.ansible.com/ansible/latest/user_guide/become.html#risks-of-becoming-an-unprivileged-user
  become_user: "{{ aegir_user }}"
  when: aegir_provision_git_deploy_result.changed | bool

- name: Disable globally readable Ansible command files
  set_fact:
    allow_world_readable_tmpfiles: no
