---

- name: Deploy Provision from custom repo and/or branch.
  git:
    repo: "{{ aegir_provision_repo }}"
    dest: "{{ aegir_root }}/.drush/provision"
    update: "{{ aegir_provision_update }}"
    version: "{{ aegir_provision_version }}"
  become: yes
  become_user: "{{ aegir_user }}"

- name: Clear Drush cache for Provision extension
  shell: drush @none cc drush
  args:
    creates: "{{ aegir_root }}/.drush/cache/"
  become: yes
  become_user: "{{ aegir_user }}"

