---

- name: "Check if extra module {{ aegir_extra_module }} is enabled"
  shell: "drush @hostmaster pm-info --fields=status --format=list {{ aegir_extra_module }} | egrep 'enabled'"
  become: True
  become_user: "{{ aegir_user }}"
  register: aegir_extra_module_enabled
  changed_when: False
  failed_when: False
  ignore_errors: yes

- name: "Enable extra module {{ aegir_extra_module }}"
  shell: "drush @hostmaster --yes en {{ aegir_extra_module }} --no-verify --strict=0"
  become: True
  become_user: "{{ aegir_user }}"
  register: enable_extra_module_result
  when: (aegir_extra_module_enabled.rc is defined) and (aegir_extra_module_enabled.rc != 0)

- name: "Set semaphore to verify Aegir front-end after enabling module(s)."
  set_fact:
    aegir_frontend_verify_required: true
  when: enable_extra_module_result.changed | bool

