---

- debug:
    msg: Perform fix_permissions tasks.

- name: Find the hostmaster platform path.
  shell: drush @hostmaster status --fields=root --field-labels=0
  become_user: "{{ aegir_user }}"
  become: yes
  register: hostmaster_platform_path
  changed_when: false

- name: Set a fact for the hostmaster platform path
  set_fact:
    hostmaster_platform_path: "{{ hostmaster_platform_path.stdout | trim }}"

- name: Run the install script.
  # Dan - TODO: will deploy to /profiles/hostmaster/modules/aegir/ when we *don't* generate the drush makefile
  # we need to set a fact and switch on that.
  shell: "/bin/bash {{ hostmaster_platform_path }}/sites/all/modules/hosting_tasks_extra/fix_permissions/scripts/install.sh"
  args:
    creates: /etc/sudoers.d/fix-drupal-platform-permissions
  become: yes
  become_user: root

- name: Check if fix_permissions module is enabled
  shell: "drush @hostmaster pm-info --fields=status --format=list fix_permissions | egrep 'disabled|not installed'"
  become: yes
  become_user: "{{ aegir_user }}"
  register: fix_permissions_enabled
  changed_when: False
  failed_when: False
  ignore_errors: yes

- name: Enable fix_permissions module
  shell: "drush @hostmaster --yes en fix_permissions --no-verify --strict=0"
  become: yes
  become_user: "{{ aegir_user }}"
  when: fix_permissions_enabled.rc == 0
  notify: Verify Aegir front-end

