---
- name: Create the Aegir user's SSH directory if it doesn't exist
  ansible.builtin.file:
    path: "{{ aegir_ssh_directory }}"
    state: directory
    mode: '0700'
    owner: "{{ aegir_user }}"
    group: "{{ aegir_user }}"
  become: yes

- name: Generate an OpenSSH keypair
  community.crypto.openssh_keypair:
    path: "{{ aegir_ssh_directory }}/id_ed25519"
    # TODO: Remove whenever it becomes the default.
    type: ed25519
    comment: "Aegir SSH keypair"
    group: "{{ aegir_user }}"
    owner: "{{ aegir_user }}"
  become: yes
