---

- name: Generate one-time login link
  shell: "
  echo '////////////// You can access the front-end of your Aegir install at: //////////////////////';
  drush @hostmaster uli;
  "
  become: True
  become_user: "{{ aegir_user }}"
  register: aegir_login_link_output
  changed_when: False

- name: Print the login link
  debug:
    var: aegir_login_link_output.stdout_lines
  when: aegir_login_link_output.stdout_lines is defined
