---
- name: Build Hostmaster platform.
  shell: "drush make {{ aegir_makefile_path }} {{ aegir_root }}/hostmaster-{{ aegir_platform_version }} --working-copy --no-gitinfofile"
  args:
    creates: "{{ aegir_root }}/hostmaster-{{ aegir_platform_version }}/"
  become: yes
  become_user: "{{ aegir_user }}"
