---
- name: Ensure that test makefile doesn't exist.
  file:
    path: '/etc/aegir/aegir.make.yml'
    state: absent
  changed_when: False
  become: yes

- name: Use default Aegir Drush makefile.
  include: ../../tasks/makefile.yml

- name: Confirm custom Aegir Drush makefile does not exist.
  shell: "[ ! -f /etc/aegir/aegir.make.yml ]"
  changed_when: False

  # We have to reset this, since the use of the default above will override it.
- name: Reset Aegir Drush makefile path to default.
  set_fact:
    aegir_makefile_path: "/etc/aegir/aegir.make.yml"

  # Because we are deleting it above, this step will write the Aegir Drush
  # makefile every time this test is executed; this is ok.
- name: Deploy custom Aegir Drush makefile.
  include: ../../tasks/makefile.yml
  vars:
    aegir_generate_makefile: yes

- name: Check that custom Aegir Drush makefile exists.
  shell: "[ -f /etc/aegir/aegir.make.yml ]"
  changed_when: False
  become: yes

