---

- name: Clear Aegir database root password from debconf database
  shell: "echo 'UNREGISTER aegir/db_password' | debconf-communicate aegir3-hostmaster"

- name: Clear Drush cache
  shell: drush @none cc drush
  become: yes
  become_user: "{{ aegir_user }}"
  notify: Ensure that the queue daemon is running

- name: Clear Aegir front-end Drush cache
  shell: drush @hostmaster cc drush
  become: yes
  become_user: "{{ aegir_user }}"
  notify: Ensure that the queue daemon is running

- name: Verify Aegir front-end
  shell: drush @hostmaster cc drush && drush @hostmaster hosting-task @hostmaster verify --force && drush @hostmaster hosting-tasks
  become: yes
  become_user: "{{ aegir_user }}"

- name: Clear Aegir task queue lock
  shell: drush @hostmaster hosting-release-lock
  become: yes
  become_user: "{{ aegir_user }}"

- name: Ensure that the queue daemon is running
  service:
    name: hosting-queued
    state: started
  become: true
  when: aegir_use_hosting_queued |bool

- name: Restart the queue daemon
  service:
    name: hosting-queued
    state: restarted
  become: true
  when: aegir_use_hosting_queued |bool
