---
- name: Add Skynet systemd config.
  template:
    src: aegir-skynet.service.j2
    dest: /etc/systemd/system/aegir-skynet.service
  become: yes

- name: Ensure systemd service is running.
  service:
    name: aegir-skynet
    enabled: yes
    state: started
  become: yes

